name: Upload conda packages
on:
  push

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build passing"
          exit 0

  on-failure:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build failing"
          exit 1
